# permissions for end users to view producers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: producer-viewer-role
rules:
- apiGroups:
  - producers.zoracloud.ai
  resources:
  - producers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - producers.zoracloud.ai
  resources:
  - producers/status
  verbs:
  - get
