
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - producers.zoracloud.ai
  resources:
  - producers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - producers.zoracloud.ai
  resources:
  - producers/finalizers
  verbs:
  - update
- apiGroups:
  - producers.zoracloud.ai
  resources:
  - producers/status
  verbs:
  - get
  - patch
  - update
